export const strings = {
  brand: {
    name: 'Nexora',
    tagline: 'Discover Vietnam',
  },
  auth: {
    login: {
      title: 'Welcome back',
      subtitle: 'Sign in to your account',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Your password',
      submit: 'Sign in',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      register: 'Create one',
    },
    register: {
      title: 'Create account',
      subtitle: 'Start your Vietnam journey',
      fullNameLabel: 'Full name',
      fullNamePlaceholder: 'Nguyen Van A',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Min. 8 chars, 1 uppercase, 1 digit',
      confirmPasswordLabel: 'Confirm password',
      confirmPasswordPlaceholder: 'Repeat your password',
      submit: 'Create account',
      hasAccount: 'Already have an account?',
      login: 'Sign in',
      passwordMismatch: 'Passwords do not match.',
      passwordWeak: 'Password must be at least 8 characters with 1 uppercase letter and 1 digit.',
      emailInvalid: 'Please enter a valid email address.',
    },
    verify: {
      title: 'Check your inbox',
      subtitle: (email: string) =>
        `We sent a 6-digit code to ${email}. Enter it below to verify your email.`,
      codeLabel: 'Verification code',
      submit: 'Verify email',
      resend: 'Resend code',
      resendCooldown: (seconds: number) => `Resend in ${seconds}s`,
      success: 'Email verified! Welcome to Nexora.',
    },
    forgotPassword: {
      title: 'Reset password',
      subtitle: "Enter your email and we'll send you a reset link.",
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      submit: 'Send reset link',
      backToLogin: 'Back to sign in',
      successTitle: 'Check your inbox',
      successSubtitle: (email: string) =>
        `We sent a password reset link to ${email}.`,
    },
    resetPassword: {
      title: 'Set new password',
      subtitle: 'Choose a strong password for your account.',
      passwordLabel: 'New password',
      passwordPlaceholder: 'Min. 8 chars, 1 uppercase, 1 digit',
      confirmLabel: 'Confirm password',
      confirmPlaceholder: 'Repeat your new password',
      submit: 'Set password',
      passwordMismatch: 'Passwords do not match.',
    },
    twoFa: {
      title: 'Two-factor auth',
      subtitle: 'Enter the 6-digit code from your authenticator app.',
      submit: 'Verify',
      invalidCode: 'Invalid code. Please try again.',
    },
  },
  common: {
    loading: 'Loading…',
    or: 'or',
    back: 'Back',
  },
} as const;
