export const theme = {
  colors: {
    primary:       '#2D6A4F',
    primaryLight:  '#52B788',
    primaryDark:   '#1B4332',
    surface:       '#FFFFFF',
    surfaceAlt:    '#F8FAF9',
    surfaceInput:  '#F2F7F4',
    border:        '#D8E8E0',
    borderFocus:   '#52B788',
    textPrimary:   '#1A2E25',
    textSecondary: '#5C7A6A',
    textMuted:     '#8FA99A',
    textOnPrimary: '#FFFFFF',
    error:         '#C0392B',
    errorBg:       '#FDF0EF',
    errorBorder:   '#E8B4B0',
    success:       '#2D6A4F',
    successBg:     '#F0F7F4',
  },
  radius: {
    sm:  8,
    md:  12,
    lg:  20,
    xl:  28,
    full: 9999,
  },
  spacing: {
    xs:   4,
    sm:   8,
    md:   16,
    lg:   24,
    xl:   32,
    xxl:  48,
  },
  font: {
    xs:   12,
    sm:   14,
    md:   16,
    lg:   18,
    xl:   22,
    xxl:  28,
    xxxl: 36,
  },
} as const;
