// Style Dictionary build for @tourism/tokens.
// Emits generated/tokens.css (Tailwind v4 @theme inline + :root + .dark).
// Run: node libs/shared/tokens/style-dictionary/build.mjs (wired as the Nx `tokens` target).

import StyleDictionary from 'style-dictionary';
import { formatHex, formatRgb, parse } from 'culori';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import tokens, {
  radiusScale,
  fonts,
  themeExtras,
  rootExtras,
  densityCompact,
  baseRules,
} from './tokens.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, '../generated');

const HEADER =
  '/* GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand. */\n' +
  '/* Source: libs/shared/tokens/style-dictionary/ */';

const cssVar = (token) => `--${token.path.slice(1).join('-')}`;
const radiusStep = (mult) =>
  mult === 1 ? 'var(--radius)' : `calc(var(--radius) * ${mult})`;

/** OKLCH/CSS colors → hex or rgba() for React Native / Reanimated. */
function toNativeColor(value) {
  const parsed = parse(value);
  if (!parsed) return value;
  if (typeof parsed.alpha === 'number' && parsed.alpha < 1) {
    return formatRgb(parsed);
  }
  return formatHex(parsed);
}

StyleDictionary.registerFormat({
  name: 'tourism/tailwind-css',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const radius = dictionary.allTokens.find((t) => t.path[0] === 'radius');

    const theme = [
      `  --font-heading: ${fonts.heading};`,
      `  --font-sans: ${fonts.sans};`,
      ...colors.map((t) => `  --color-${t.path.slice(1).join('-')}: var(${cssVar(t)});`),
      ...Object.entries(radiusScale).map(([s, m]) => `  --radius-${s}: ${radiusStep(m)};`),
      ...themeExtras.map(([k, v]) => `  ${k}: ${v};`),
    ];
    const root = [
      ...colors.map((t) => `  ${cssVar(t)}: ${t.original.value};`),
      `  --radius: ${radius.original.value};`,
      ...rootExtras.map(([k, v]) => `  ${k}: ${v};`),
    ];
    const dark = colors.map((t) => `  ${cssVar(t)}: ${t.original.darkValue};`);

    return [
      HEADER,
      '',
      '@theme inline {',
      ...theme,
      '}',
      '',
      ':root {',
      ...root,
      '}',
      '',
      '.dark {',
      ...dark,
      '}',
      '',
      "[data-density='compact'] {",
      ...densityCompact.map(([k, v]) => `  ${k}: ${v};`),
      '}',
      '',
      '@layer base {',
      ...baseRules.map((l) => `  ${l}`),
      '}',
      '',
    ].join('\n');
  },
});

// React Native theme — hex/rgba colors (converted from oklch at build time).
StyleDictionary.registerFormat({
  name: 'tourism/rn-theme',
  format: ({ dictionary }) => {
    const colors = dictionary.allTokens.filter((t) => t.path[0] === 'color');
    const radius = dictionary.allTokens.find((t) => t.path[0] === 'radius');
    const key = (t) => t.path.slice(1).join('-');
    const entries = (pick) =>
      colors.map((t) => `      '${key(t)}': '${toNativeColor(pick(t))}',`).join('\n');

    return [
      '// GENERATED by @tourism/tokens (Style Dictionary). Do not edit by hand.',
      '// RN theme — colors converted to hex/rgba for React Native and Reanimated.',
      'export const theme = {',
      '  colors: {',
      '    light: {',
      entries((t) => t.original.value),
      '    },',
      '    dark: {',
      entries((t) => t.original.darkValue),
      '    },',
      '  },',
      `  radius: { base: '${radius.original.value}' },`,
      '};',
      '',
      'export default theme;',
      '',
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  tokens,
  log: { verbosity: 'silent' },
  platforms: {
    tailwind: {
      // No value transforms — emit oklch strings verbatim; names come from token paths.
      transforms: [],
      buildPath: `${outDir}/`,
      files: [
        { destination: 'tokens.css', format: 'tourism/tailwind-css' },
        { destination: 'theme.js', format: 'tourism/rn-theme' },
      ],
    },
  },
});

await sd.buildAllPlatforms();
console.log(`tokens.css written to ${outDir}`);
